@server = http://localhost:4004
@me = Authorization: Basic {{$processEnv USER}}:
@basic = Authorization: Basic admin:admin
### ------------------------------------------------------------------------
# Get Weight
GET  {{server}}/v2/catalog/getWeight 
content-type: application/json
{{me}}



### ------------------------------------------------------------------------
# Get Parcel
GET  {{server}}/v2/catalog/Parcel(203ef2a8-2b65-4694-bbc9-6ff3d3243849) 
content-type: application/json
{{me}}


### ------------------------------------------------------------------------
# Get CargoReceipt
GET  {{server}}/v2/catalog/CargoReceipt(c95cddc6-077e-4a78-aaaa-b90e82419d79) 
content-type: application/json
{{me}}


### ------------------------------------------------------------------------
# Get CargoReceipt
PATCH   {{server}}/v2/catalog/CargoReceipt(c95cddc6-077e-4a78-aaaa-b90e82419d79) 
content-type: application/json
{{me}} 

{
    "image": ""
}

